title: Feather Fall
description: >
  A baby goose. A dangerous cliff. And a hungry eagle. Help guide the chick as it falls down the cliff. Go too fast and the chick is harmed on impact with the ground. Go too slow and the eagle catches up to its delicious dinner. Bump into the rocks and branches to keep control of the speed. (Go for the branches, they won't hurt as much.) And get the chick safely to the ground. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman